// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RTQxF0a7qVGaMGOJ3-_xKIMnspGj0yg',
    appId: '1:994442717056:web:008fb8657270c1f0d68365',
    messagingSenderId: '994442717056',
    projectId: 'fir-flutter-app-1a130',
    authDomain: 'fir-flutter-app-1a130.firebaseapp.com',
    storageBucket: 'fir-flutter-app-1a130.firebasestorage.app',
    measurementId: 'G-R4JDVSXSHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvPOp54uNXlL09iXGBtvEzZI2MQYqlnwQ',
    appId: '1:994442717056:android:74999939bbd5e0ffd68365',
    messagingSenderId: '994442717056',
    projectId: 'fir-flutter-app-1a130',
    storageBucket: 'fir-flutter-app-1a130.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLsZOuQVLroXB9JkrIN3xda0g7yOWcaQ',
    appId: '1:994442717056:ios:9f3d9789b6c445cbd68365',
    messagingSenderId: '994442717056',
    projectId: 'fir-flutter-app-1a130',
    storageBucket: 'fir-flutter-app-1a130.firebasestorage.app',
    iosBundleId: 'com.example.project10FirebaseLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtLsZOuQVLroXB9JkrIN3xda0g7yOWcaQ',
    appId: '1:994442717056:ios:9f3d9789b6c445cbd68365',
    messagingSenderId: '994442717056',
    projectId: 'fir-flutter-app-1a130',
    storageBucket: 'fir-flutter-app-1a130.firebasestorage.app',
    iosBundleId: 'com.example.project10FirebaseLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8RTQxF0a7qVGaMGOJ3-_xKIMnspGj0yg',
    appId: '1:994442717056:web:813efddc51595523d68365',
    messagingSenderId: '994442717056',
    projectId: 'fir-flutter-app-1a130',
    authDomain: 'fir-flutter-app-1a130.firebaseapp.com',
    storageBucket: 'fir-flutter-app-1a130.firebasestorage.app',
    measurementId: 'G-Z6QN79KHVY',
  );

}